project/about/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'about'

urlpatterns = [
    path(
        '',
        TemplateView.as_view(template_name='about/description.html'),
        name='description'
    )
]

project/homepage/urls.py
from django.urls import path, re_path

from . import views

app_name = 'homepage'

urlpatterns = [
    path(
        '',
        views.HomeView.as_view(),
        name='home'
    ),
    path(
        'create_post/',
        views.CreatePostView.as_view(),
        name='create_post'
    ),
    path(
        'create_tag/',
        views.CreateTagView.as_view(),
        name='create_tag'
    ),
    re_path(
        r'^post/(?P<pk>[1-9][0-9]*)/$',
        views.PostDetailView.as_view(),
        name='post'
    ),
    re_path(
        r'^like/(?P<pk>[1-9][0-9]*)/$',
        views.likeView,
        name='like'
    )
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('about/', include('about.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

project/users/urls.py
import django.contrib.auth.views as auth_views
from django.urls import path, re_path

from . import views

app_name = 'users'


urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='users/login.html'
        ),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(
            template_name='users/logout.html'
        ),
        name='logout'
    ),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='users/password_change.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'password_reset/confirm/<uidb64>',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'password_reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_  complete'
    ),
    path(
        'signup/',
        views.SignUpView.as_view(),
        name='signup'
    ),
    path(
        'profile/',
        views.ProfileView.as_view(),
        name='profile'
    ),
    re_path(
        r'^user_detail/(?P<pk>[1-9][0-9]*)/$',
        views.UserDetailView.as_view(),
        name='user_detail'
    ),
]

project/templates/includes/base_form.html
{% load add_attr %}
{% load field_type %}
<style>
    .form-control {
        min-width: 300px;
        width: 75%;
    }
</style>
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger" role="alert">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}
<form method="post" action="" style="margin-top: 20px;" id="form">

  {% csrf_token %}
  <ul>
    {% for field in form.hidden_fields %}
      {% if field|field_type == "SelectMultiple" %}
        {{ field|add_attr:"class:selectpicker, data-style: btn-secondary" }}
      {% else %}
        {{ field|add_attr:"class:form-control dark-input" }}
      {% endif %}
    {% endfor %}
    {% for field in form.visible_fields %}
      <label for="{{ field.id_for_label }}" class="col-sm-8 col-form-label">
        {{ field.label }}
        {% if field.field.required %}
          <span style="color: red;">*</span>
        {% endif %}
      </label>
      <div class="col-sm-8">
        {% if field|field_type == "SelectMultiple" %}
          {{ field|add_attr:"class:selectpicker, data-style: btn-secondary" }}
        {% else %}
          {{ field|add_attr:"class:form-control dark-input" }}
        {% endif %}
        {% if field.help_text %}
        <div id="{{ field.id_for_label }}-help" class="form-text">
          {{ field.help_text|safe }}
        </div>
        {% endif %}
      </div>
    {% endfor %}
    {% if form %}
    <div>
      <button class="btn-send" type="submit" href="{% url 'homepage:home' %}" style="margin-top: 20px;">Send</button>
    </div>
    {% endif %}
  </ul>
</form>

project/templates/includes/footer.html
<div class="container">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="{% url "homepage:home" %}" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="{% url "about:description" %}" class="nav-link px-2 text-muted">About us</a></li>
      </ul>
      <p class="text-center text-muted">© {% now 'Y' %} Company, Inc</p>
  </div>

project/templates/includes/header.html
{% load static %}

<nav class="navbar navbar-expand-sm navbar-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'homepage:home' %}">YaCoder</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% with request.resolver_match.view_name as view_name %}
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a {% if view_name == 'homepage:create_post' %}class="nav-link active"{% else %}class="nav-link"{% endif %}aria-current="page" href="{% url 'homepage:create_post' %}">Create Post</a>
          </li>
          <li class="nav-item">
            <a {% if view_name == 'homepage:home' %}class="nav-link active"{% else %}class="nav-link"{% endif %}aria-current="page" href="{% url 'homepage:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a {% if view_name == 'about:description' %}class="nav-link active"{% else %}class="nav-link"{% endif %} aria-current="page" href="{% url 'about:description' %}">About</a>
          </li>
        </ul>
        <ul class="navbar-nav mb-2 mb-lg-0">
          {% if user.is_authenticated %}
            {% if user.profile_pic %}
              <img class="header-avatar" src="{{ user.profile_pic.url }}" alt="">
            {% else %}
              <img class="header-avatar" src="{% static 'img/def_profile_pic.jpg' %}" alt="">
            {% endif %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">{{ user.username }}</a>
              <ul class="dropdown-menu dropdown-menu-end">
                <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile Settings</a></li>
                <li><a class="dropdown-item" href="{% url 'users:password_change' %}">Change password</a></li>
                <li><a class="dropdown-item" href="{% url 'users:user_detail' request.user.pk %}">Your profile</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'users:logout' %}" style="color: red;">Log out</a></li>
              </ul>
            </li>
          {% else %}
          <a {% if view_name == 'users:login' %}class="nav-link active"{% else %}class="nav-link"{% endif %} href="{% url 'users:login' %}">Log in</a>

          <a class="signup" href="{% url 'users:signup' %}">Sign up</a>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </div>
</nav>