project/about/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'about'

urlpatterns = [
    path(
        '',
        TemplateView.as_view(template_name='about/description.html'),
        name='description'
    )
]

project/homepage/urls.py
from django.urls import path, re_path

from . import views

app_name = 'homepage'

urlpatterns = [
    path(
        '',
        views.HomeView.as_view(),
        name='home'
    ),
    path(
        'create_post/',
        views.CreatePostView.as_view(),
        name='create_post'
    ),
    path(
        'create_tag/',
        views.CreateTagView.as_view(),
        name='create_tag'
    ),
    re_path(
        r'^post/(?P<pk>[1-9][0-9]*)/$',
        views.PostDetailView.as_view(),
        name='post'
    ),
    re_path(
        r'^like/(?P<pk>[1-9][0-9]*)/$',
        views.likeView,
        name='like'
    )
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('about/', include('about.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

project/users/urls.py
import django.contrib.auth.views as auth_views
from django.urls import path, re_path

from . import views

app_name = 'users'


urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='users/login.html'
        ),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(
            template_name='users/logout.html'
        ),
        name='logout'
    ),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='users/password_change.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'password_reset/confirm/<uidb64>',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'password_reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_  complete'
    ),
    path(
        'signup/',
        views.SignUpView.as_view(),
        name='signup'
    ),
    path(
        'profile/',
        views.ProfileView.as_view(),
        name='profile'
    ),
    re_path(
        r'^user_detail/(?P<pk>[1-9][0-9]*)/$',
        views.UserDetailView.as_view(),
        name='user_detail'
    ),
]

project/users/models.py
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin,
                                        UserManager)
from django.db import models
from django.urls import reverse


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        'username',
        max_length=127,
        help_text='127 symbols max',
    )
    email = models.EmailField(
        'email',
        max_length=254,
        unique=True,
        help_text='254 symbols max',
    )

    first_name = models.CharField(
        'first name',
        max_length=127,
        blank=True,
        null=True,
        help_text='127 symbols max',
    )
    last_name = models.CharField(
        'last name',
        max_length=127,
        blank=True,
        null=True,
        help_text='127 symbols max',
    )
    about_me = models.TextField(
        'about me',
        default='no bio yet',
        blank=True,
    )
    profile_pic = models.ImageField(
        'profile picture',
        upload_to='images/%Y/%m',
        blank=True,
    )

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ('username',)

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'
        default_related_name = 'users'

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:user_detail', kwargs={"pk": self.pk})

project/users/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import User


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            User.username.field.name,
            User.email.field.name,
            'password1',
            'password2',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class ProfileForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = (
            User.email.field.name,
            User.username.field.name,
            User.first_name.field.name,
            User.last_name.field.name,
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

project/users/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView

from .forms import ProfileForm, SignUpForm
from .models import User


class SignUpView(CreateView):
    template_name = 'users/signup.html'
    form_class = SignUpForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('homepage:home')

    def form_invalid(self, form):
        return render(self.request, 'users/signup.html',
                      {'form': form})

    def get_form(self):
        return SignUpForm(self.request.POST or None)


class ProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/profile.html'
    pk = 1
    model = User
    form_class = ProfileForm

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        form.save()
        return redirect('homepage:home')

    def get_form(self):
        return ProfileForm(self.request.POST or None,
                           instance=self.request.user)


class UsersView(ListView):

    template_name = 'users/user_list.html'
    model = User
    context_object_name = 'users'

    def get_queryset(self):
        return User.objects.filter(is_active=True)


class UserDetailView(DetailView):
    template_name = 'users/user_detail.html'
    model = User
    context_object_name = 'disp_user'

    def get_object(self):
        return get_object_or_404(User, pk=self.kwargs['pk'])

project/templates/users/login.html
{% extends 'base.html' %}
{% load static %} 

{% block title %}
Log in :: {{ block.super }}
{% endblock %}

{% block content %}
<div class="card-form mx-auto mb-auto bg-dark">
  <div class="card-body mx-auto">
    <h5 class="card-title">Log in</h5>
    {% block form %}
    {% include 'includes/base_form.html' %}
    <small style="color: #8f8f8f; padding-left: 32px;"><a href="{% url 'users:password_reset' %}" style="text-decoration: none;">Forgot the password?</a></small>
    {% endblock %}
  </div>
</div>
{% endblock %}

project/templates/users/password_change.html
{% extends 'base.html' %}
{% load static %} 

{% block title %}
Change password :: {{ block.super }}
{% endblock %}

{% block content %}
  <div class="container">
    <div class="ml-2">
      <h3 style="color: #8f8f8f;">Change password</h3>
      <hr>
    </div>
    {% block form %}
        {% include 'includes/base_form.html' %}
        <a href=""></a>
    {% endblock %}
  </div>
{% endblock %}

project/templates/users/password_change_done.html
{% extends 'base.html' %}
{% load static %} 

{% block title %}
Change password :: {{ block.super }}
{% endblock %}

{% block content %}
  <div class="container">
    <div class="card-form mx-auto mb-3 bg-dark" style="max-width: 18rem;">
      <div class="card-body mx-auto">
        <h5 class="card-title">Password changed</h5>
        <p class="card-text" style="color: #ffffff;">Password was succsessfully changed!</p>
        <a href="{% url 'homepage:home' %}" class="btn btn-danger">To Home</a>
      </div>
    </div>
  </div>
{% endblock %}

project/templates/users/password_reset.html
{% extends 'base.html' %}
{% load static %} 

{% block title %}
Reset password :: {{ block.super }}
{% endblock %}

{% block content %}
<div class="card-form mx-auto mb-auto bg-dark" style="max-width: 80rem;">
    <div class="card-body mx-auto">
      <h5 class="card-title">Reset password</h5>
      {% block form %}
        {% include 'includes/base_form.html' %}
      {% endblock %}
    </div>
  </div>
{% endblock %}

project/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load static %} 

{% block title %}
Успешное восстановление пароля :: {{ block.super }}
{% endblock %}

{% block content %}
    <div class="card-form mx-auto mb-auto bg-dark" style="max-width: 32rem;">
        <div class="card-body mx-auto">
        <h5 class="card-title">Password succsessfully reseted</h5>
        {% block form %}
            {% include 'includes/base_form.html' %}
        {% endblock %}
        </div>
    </div>

{% endblock %}

project/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %} 

{% block title %}
Восстановление пароля :: {{ block.super }}
{% endblock %}

{% block content %}
<div class="card-form mx-auto mb-auto bg-dark" style="max-width: 32rem;">
    <div class="card-body mx-auto">
      <h5 class="card-title">Confirm reset password</h5>
      {% block form %}
        {% include 'includes/base_form.html' %}
      {% endblock %}
    </div>
  </div>
{% endblock %}

project/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load static %} 

{% block title %}
Восстановление пароля :: {{ block.super }}
{% endblock %}

{% block content %}
    <div class="card-form mx-auto mb-auto bg-dark" style="max-width: 32rem;">
        <div class="card-body mx-auto">
        <h5 class="card-title">Проверьте вашу электронную почту.</h5>
        <p class="card-text" style="color: #ffffff;">Мы отправили вам сообщение с дальнейшими инструкциями по изменению пароля</p>
        </div>
    </div>
{% endblock %}

project/templates/users/profile.html
{% extends 'base.html' %}
{% load static %} 

{% block title %}
Your profile :: {{ block.super }}
{% endblock %}

{% block content %}
  <div class="container">
    <div class="ml-2">
      <h2>{{ user.username }}</h2>
      <h3 style="color: #8f8f8f;">Change profile</h3>
      <hr>
    </div>
    {% block form %}
        {% include 'includes/base_form.html' %}
    {% endblock %}
  </div>
{% endblock %}

project/templates/users/signup.html
{% extends 'base.html' %}
{% load static %} 

{% block title %}
Sign up :: {{ block.super }}
{% endblock %}

{% block content %}
<div class="card-form mx-auto mb-auto bg-dark">
  <div class="card-body mx-auto">
    <h5 class="card-title">Sign up</h5>
    {% block form %}
    {% include 'includes/base_form.html' %}
    <small style="color: #8f8f8f; padding-left: 32px;"><a href="{% url 'users:password_reset' %}" style="text-decoration: none;">Forgot the password?</a></small>
    {% endblock %}
  </div>
</div>
{% endblock %}

project/templates/users/user_detail.html
{% extends 'base.html' %}
{% load static %} 

{% block title %}
{{ disp_user.username }} :: {{ block.super }}
{% endblock %}
{% block content %}
  <div class="container">
    <div class="row userrow">
      <div class="col-4 userinfo">
        <div class="username">{{ disp_user.username }}</div>
        {% if disp_user.profile_pic %}
        <img src="{{ disp_user.profile_pic.url }}" class="avatar"></img>
        {% else %}
        <img src="{% static 'img/def_profile_pic.jpg' %}" class="avatar"></img>
        {% endif %}
        <div class="bio">
          <h4>About me:</h4>
          {{ disp_user.about_me }}
        </div>
      </div>
    </div>
    <div class="row">
    <div class="col-4"></div>
    <div class="col-8 posts">
      {% for post in disp_user.posts.all %}
      <div class="post-min">
        <div class="row">
          <div class="col-8">
            <pre><code>{{ post.code|truncatechars:800}}</code></pre>
          </div>
          <div class="col-4 post-about">
            <h2>{{ post.name }}</h2>
            <div class="post-desc">
              {{post.text|truncatechars:100}}
            </div>
            <div class="viewfull"><a href="{{ post.get_absolute_url }}" class="viewfull-btn">view full post</a></div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}
    